### ISSUE TITLE
About preprocessing the US election datasets

### ISSUE THREAD

**Issue by Kqiii** [JunwenBai/correlation-gnn#1]
Hi,

May I ask if you can share the code you used to preprocess the [raw data of US election](https://github.com/000Justin000/gnn-residual-correlation/tree/master/datasets/election)? Specifically, I would like to know how you turn the [adjacency.txt](https://github.com/000Justin000/gnn-residual-correlation/blob/master/datasets/election/adjacency.txt) the original repo into the A.npy here.

Thank you very much!

**Comment by JunwenBai** [comment]
The data was directly copied from this [repo](https://github.com/000Justin000/gnn-residual-correlation). I don't know how they preprocessed the raw data.

**Comment by Kqiii** [comment]
> The data was directly copied from this [repo](https://github.com/000Justin000/gnn-residual-correlation). I don't know how they preprocessed the raw data.

Thank you for your prompt reply!
