### ISSUE TITLE
About Data preprocessing

### ISSUE THREAD

**Issue by padmaksha18** [JunwenBai/correlation-gnn#2]
Hello authors, can you please guide me on how the A.npy file is formed from the adjacency.txt in the original data. I need to change the edge between counties with mobility data, so just wanted to know how to form it. Can you also elaborate a little bit on the other files in the /data directory as well , I mean how they are generated from the raw data. Thanks!

**Comment by JunwenBai** [comment]
Answered [here](https://github.com/000Justin000/gnn-residual-correlation/issues/1).
